---
title: "Activity 5"
author: "Name here"
output: pdf_document
---


### Q1. "Integration"

Solve the following integrals, and write a short summary of why your results are valid.

1. $\int \frac{\Gamma(a) \Gamma(b)}{\Gamma(a+b)} \theta^{(a-1)} (1- \theta)^{(b-1)} d\theta$ 

2. $\int \theta^{(a-1)} (1- \theta)^{(b-1)} d\theta$ 

3. $\int \theta^{(a-1)} (1-\theta)^{(b-1)} \theta^z (1-\theta)^{(N-z)} d\theta$

### Q2. Posterior Mean - weighted combination

Assume you are interested in estimating $\theta$, a probability of an event occurring. You have placed a beta prior distribution on $\theta$ with parameters $a$ and $b$. You've also collected $N$ independent trials and observed $z$ successes. This results in a posterior distribution ($\theta|N,z$) that is beta($a + z, b + N - z).$

Consider the mean of this posterior distribution $\frac{z+a}{N+a+b}$, which can be rewritten as below.


\begin{eqnarray}
\frac{z+a}{N+a+b} &=& \frac{z}{N+a+b} + \frac{a}{N+a+b} \\
&=&\frac{N}{N}\frac{z}{N+a+b} + \frac{a+b}{a+b}\frac{a}{N+a+b}\\
&=&\frac{z}{N}\frac{N}{N+a+b} + \frac{a}{a+b}\frac{a+b}{N+a+b}\\
\end{eqnarray}

Discuss how the posterior mean is a weighted average of the data mean and the prior mean.

What are the weights for each component?


### Q3. DBDA Exercise 6.4. 

#### a. 
[Purpose: To explore an unusual prior and learn about the beta distribution in the process.] Suppose we have a coin that we know comes from a magic-trick store, and therefore we believe that the coin is strongly biased either usually to come up heads or usually to come up tails, but we don’t know which. Express this belief as a beta prior. (Hint: See Figure 6.1, upper-left panel.) 



#### b.
Now we flip the coin 5 times and it comes up heads in 4 of the 5 flips. What is the posterior distribution? 


#### c.
Create a plot of your posterior distribution and create a line to denote the posterior mean.


### 4. Exercise 6.5. 

[Purpose: To get hands on experience with the goal of predicting the next datum, and to see how the prior influences that prediction.]

#### a.
Suppose you have a coin that you know is minted by the government and has not been tampered with. Therefore you have a strong prior belief that the coin is fair. _Say, Beta(10,10)_ You flip the coin 10 times and get 9 heads. What is your predicted probability of heads for the 11th flip (as a 95% interval)? Explain your answer carefully; justify this choice of prior.

#### b.
Now you have a different coin, this one made of some strange material and marked (in fine print) “Patent Pending, International Magic, Inc.” _You opt for an uniformative prior (Beta(1,1)). You flip the coin 10 times and get 9 heads. What is your predicted probability of heads for the 11th flip  (as a 95% interval)? Explain your answer carefully; justify this choice of prior.

### 5. Data Analysis
Use a dataset containing homes in the Seattle, WA area [http://www.math.montana.edu/ahoegh/teaching/stat408/datasets/SeattleHousing.csv](http://www.math.montana.edu/ahoegh/teaching/stat408/datasets/SeattleHousing.csv) for this question.


Estimate the posterior distribution for the probability that houses in Seattle have more than 3 bedrooms.
```{r}
library(tidyverse)
seattle <- read_csv('http://www.math.montana.edu/ahoegh/teaching/stat408/datasets/SeattleHousing.csv') 
```

### 6. Monte Carlo Techniques

We have previously used simulation, in the form of Monte Carlo techniques, to estimate probabilities of outcomes. Soon we will use Monte Carlo techniques to assist with summarizing posterior distributions.

For the following distributions:

1. calculate an exact mean and 95% interval (a quantile based-approach is fine)
2. simulate 1000 samples from the distribution, then calculate an approximate mean and 95% interval 
3. simulate 10000 samples from the distribution, then calculate an approximate mean and 95% interval 
4. simulate 100,000 samples from the distribution, then calculate an approximate mean and 95% interval 


### a
Beta(1,1)

### b
Beta(10,1)

### c
Beta(10,90)

### d
Comment how effective the Monte Carlo techniques are at estimating these properties of the distributions.